import type { Note, Tag, Notebook } from "./types";

export const mockNotebooks: Notebook[] = [
  { id: "nb1", name: "Work Projects", stack: "Professional" },
  { id: "nb2", name: "Personal Ideas", stack: "Personal" },
  { id: "nb3", name: "Research", stack: "Professional" },
  { id: "nb4", name: "Journal", stack: "Personal" },
  { id: "nb5", name: "Recipes", stack: "Personal" },
  { id: "nb6", name: "Tech Notes", stack: "Professional" },
];

export const mockTags: Tag[] = [
  { id: "t1", name: "javascript" },
  { id: "t2", name: "react" },
  { id: "t3", name: "design" },
  { id: "t4", name: "meeting" },
  { id: "t5", name: "ideas" },
  { id: "t6", name: "todo" },
  { id: "t7", name: "python" },
  { id: "t8", name: "machine-learning" },
  { id: "t9", name: "cooking" },
  { id: "t10", name: "travel" },
  { id: "t11", name: "books" },
  { id: "t12", name: "health" },
  { id: "t13", name: "finance" },
  { id: "t14", name: "productivity" },
  { id: "t15", name: "architecture" },
  { id: "t16", name: "api" },
  { id: "t17", name: "database" },
  { id: "t18", name: "devops" },
];

export const mockNotes: Note[] = [
  {
    id: "n1",
    title: "React Component Architecture",
    snippet: "Notes on building scalable React component architecture with compound components and hooks patterns. Related to API Design Patterns.",
    notebookId: "nb6",
    tagIds: ["t1", "t2", "t15"],
    created: Date.now() - 86400000 * 30,
    updated: Date.now() - 86400000 * 2,
  },
  {
    id: "n2",
    title: "Q1 Planning Meeting Notes",
    snippet: "Discussed roadmap for Q1. Key topics: new dashboard, API redesign, team hiring. Follow up on Machine Learning Integration Project.",
    notebookId: "nb1",
    tagIds: ["t4", "t6"],
    created: Date.now() - 86400000 * 15,
    updated: Date.now() - 86400000 * 15,
  },
  {
    id: "n3",
    title: "Machine Learning Integration Project",
    snippet: "Plan for integrating ML models into production. Using Python FastAPI backend with TensorFlow serving. Check Database Optimization Guide for perf tips.",
    notebookId: "nb3",
    tagIds: ["t7", "t8", "t16"],
    created: Date.now() - 86400000 * 45,
    updated: Date.now() - 86400000 * 5,
  },
  {
    id: "n4",
    title: "Design System v2 Proposal",
    snippet: "New design system with tokens, components, and documentation. Inspired by React Component Architecture patterns.",
    notebookId: "nb1",
    tagIds: ["t3", "t2"],
    created: Date.now() - 86400000 * 20,
    updated: Date.now() - 86400000 * 3,
  },
  {
    id: "n5",
    title: "Travel Plans - Japan 2025",
    snippet: "Itinerary for Japan trip. Tokyo, Kyoto, Osaka. Must try the Homemade Ramen Recipe there. Book recommendations from Reading List 2025.",
    notebookId: "nb4",
    tagIds: ["t10", "t5"],
    created: Date.now() - 86400000 * 60,
    updated: Date.now() - 86400000 * 10,
  },
  {
    id: "n6",
    title: "Homemade Ramen Recipe",
    snippet: "Tonkotsu broth base. 12 hour simmer. Chashu pork belly, ajitama eggs, green onions, nori.",
    notebookId: "nb5",
    tagIds: ["t9"],
    created: Date.now() - 86400000 * 90,
    updated: Date.now() - 86400000 * 30,
  },
  {
    id: "n7",
    title: "API Design Patterns",
    snippet: "REST vs GraphQL comparison. Rate limiting strategies. Authentication with JWT. Related to Database Optimization Guide.",
    notebookId: "nb6",
    tagIds: ["t16", "t1", "t15"],
    created: Date.now() - 86400000 * 25,
    updated: Date.now() - 86400000 * 7,
  },
  {
    id: "n8",
    title: "Weekly Health Tracker",
    snippet: "Tracking exercise, sleep, and nutrition. Goal: 10k steps daily. See Morning Routine Optimization.",
    notebookId: "nb4",
    tagIds: ["t12", "t14"],
    created: Date.now() - 86400000 * 7,
    updated: Date.now() - 86400000 * 1,
  },
  {
    id: "n9",
    title: "Investment Portfolio Review",
    snippet: "Q4 review of investment allocations. Rebalance needed. Tech stocks overweight.",
    notebookId: "nb4",
    tagIds: ["t13"],
    created: Date.now() - 86400000 * 14,
    updated: Date.now() - 86400000 * 14,
  },
  {
    id: "n10",
    title: "Reading List 2025",
    snippet: "Books to read this year. Currently reading: Designing Data-Intensive Applications. Related to Database Optimization Guide.",
    notebookId: "nb2",
    tagIds: ["t11", "t5"],
    created: Date.now() - 86400000 * 100,
    updated: Date.now() - 86400000 * 4,
  },
  {
    id: "n11",
    title: "Database Optimization Guide",
    snippet: "Indexing strategies, query optimization, connection pooling. PostgreSQL specific tips. Used in Machine Learning Integration Project.",
    notebookId: "nb6",
    tagIds: ["t17", "t16"],
    created: Date.now() - 86400000 * 35,
    updated: Date.now() - 86400000 * 8,
  },
  {
    id: "n12",
    title: "Docker & Kubernetes Setup",
    snippet: "Container orchestration notes. Helm charts, service mesh with Istio. CI/CD pipeline integration.",
    notebookId: "nb6",
    tagIds: ["t18", "t15"],
    created: Date.now() - 86400000 * 40,
    updated: Date.now() - 86400000 * 12,
  },
  {
    id: "n13",
    title: "Morning Routine Optimization",
    snippet: "Wake at 6am. Meditation 10min. Exercise 30min. Cold shower. Journaling. See Weekly Health Tracker for progress.",
    notebookId: "nb2",
    tagIds: ["t14", "t12"],
    created: Date.now() - 86400000 * 50,
    updated: Date.now() - 86400000 * 2,
  },
  {
    id: "n14",
    title: "Python Data Pipeline",
    snippet: "ETL pipeline using Apache Airflow. Data validation with Pydantic. Connects to Machine Learning Integration Project.",
    notebookId: "nb3",
    tagIds: ["t7", "t17", "t18"],
    created: Date.now() - 86400000 * 28,
    updated: Date.now() - 86400000 * 6,
  },
  {
    id: "n15",
    title: "Startup Ideas Brainstorm",
    snippet: "Ideas for side projects. AI-powered note taking, design tool marketplace, recipe sharing app.",
    notebookId: "nb2",
    tagIds: ["t5", "t3"],
    created: Date.now() - 86400000 * 55,
    updated: Date.now() - 86400000 * 20,
  },
  {
    id: "n16",
    title: "Team Standup Template",
    snippet: "Daily standup format. Yesterday, today, blockers. Keep it under 15 minutes. Reference Q1 Planning Meeting Notes for priorities.",
    notebookId: "nb1",
    tagIds: ["t4", "t14"],
    created: Date.now() - 86400000 * 18,
    updated: Date.now() - 86400000 * 1,
  },
  {
    id: "n17",
    title: "React State Management Comparison",
    snippet: "Redux vs Zustand vs Jotai vs React Context. Performance benchmarks. See React Component Architecture for patterns.",
    notebookId: "nb6",
    tagIds: ["t1", "t2"],
    created: Date.now() - 86400000 * 22,
    updated: Date.now() - 86400000 * 9,
  },
  {
    id: "n18",
    title: "Sourdough Bread Recipe",
    snippet: "Starter feeding schedule. 72-hour fermentation process. Baking at 450F with dutch oven.",
    notebookId: "nb5",
    tagIds: ["t9"],
    created: Date.now() - 86400000 * 80,
    updated: Date.now() - 86400000 * 25,
  },
  {
    id: "n19",
    title: "GraphQL Schema Design",
    snippet: "Schema-first vs code-first approach. Pagination with cursor-based connections. Related to API Design Patterns.",
    notebookId: "nb6",
    tagIds: ["t1", "t16", "t15"],
    created: Date.now() - 86400000 * 32,
    updated: Date.now() - 86400000 * 11,
  },
  {
    id: "n20",
    title: "Meditation Journal",
    snippet: "Daily meditation practice log. Vipassana technique. 10-day retreat notes. Connected to Morning Routine Optimization.",
    notebookId: "nb4",
    tagIds: ["t12", "t14"],
    created: Date.now() - 86400000 * 70,
    updated: Date.now() - 86400000 * 1,
  },
  {
    id: "n21",
    title: "Pasta Carbonara Authentic",
    snippet: "Traditional Roman recipe. Guanciale, pecorino romano, eggs, black pepper. No cream ever.",
    notebookId: "nb5",
    tagIds: ["t9", "t10"],
    created: Date.now() - 86400000 * 65,
    updated: Date.now() - 86400000 * 40,
  },
  {
    id: "n22",
    title: "Frontend Performance Audit",
    snippet: "Lighthouse scores, Core Web Vitals optimization. Lazy loading, code splitting, image optimization. See React Component Architecture.",
    notebookId: "nb1",
    tagIds: ["t1", "t2", "t3"],
    created: Date.now() - 86400000 * 12,
    updated: Date.now() - 86400000 * 3,
  },
  {
    id: "n23",
    title: "Book Notes: Atomic Habits",
    snippet: "Key takeaways from Atomic Habits by James Clear. 1% improvements. Habit stacking. Environment design. From Reading List 2025.",
    notebookId: "nb2",
    tagIds: ["t11", "t14"],
    created: Date.now() - 86400000 * 42,
    updated: Date.now() - 86400000 * 15,
  },
  {
    id: "n24",
    title: "Microservices Communication Patterns",
    snippet: "Event-driven architecture, saga pattern, CQRS. Message brokers: Kafka vs RabbitMQ. See Docker & Kubernetes Setup for deployment.",
    notebookId: "nb3",
    tagIds: ["t15", "t18", "t16"],
    created: Date.now() - 86400000 * 38,
    updated: Date.now() - 86400000 * 13,
  },
  {
    id: "n25",
    title: "Personal Finance Dashboard",
    snippet: "Building a dashboard to track expenses. Using Python for data aggregation. Related to Investment Portfolio Review.",
    notebookId: "nb2",
    tagIds: ["t7", "t13", "t5"],
    created: Date.now() - 86400000 * 48,
    updated: Date.now() - 86400000 * 16,
  },
];
